### ISSUE TITLE
glftpos=right option broken for nlevel gloss

### ISSUE THREAD

**Issue by peteraisher** [frampton/ExPex#2]
Side by side gloss and translation is broken when using `glstyle=nlevel`. The `glftpos=right` option is ignored if it comes before `glstyle=nlevel` and causes errors if it comes after.

It looks like `\glft` is redefined by the `gfltpos` option on lines `expex.tex:1313` and `1317`, but also by the `glstyle` option on lines `715` and `720`, but in a way that is not reconcilable.

Sadly my understanding ends there!

**Comment by frampton** [comment]
I will look into it and see what is going on.

**Comment by peteraisher** [comment]
Thanks for the quick response!

Peter Aisher | Tenor
www.peteraisher.com

**Comment by frampton** [comment]
Hi Peter,

Most people who ask questions about ExPex are linguists, so I googled 
you to find out where you were.  Needless to say, I was a bit surprised. 
  I'm not a musician, but I also pedaled to work on a bike, for similar 
reasons.  And did long rides.  I also started out in physics.  So there 
is something in common.

How did you find out about ExPex and what is your particular interest in 
it?  How do you plan to use it?  I am always on the lookout for 
interesting applications.  The next edition of the User's Manual will 
contain several extensive examples.

Not many linguists use the nlevel gloss style, because it is not the way 
they were brought up to lay out glosses.  They tend to think of a gloss 
as a big array, rather than a sequence of words with things attached to 
them.  Daniel Harbour (Queen Mary University in London) is one of the 
few.  Since it is not used much, it is not surprising that all the bugs 
have not been found.  So thanks for finding one.  I'm right in the 
middle of racking my brains about something else, but I will get to 
fixing it sometime soon.

Best,
John

**Comment by peteraisher** [comment]
Hi John,

Nice to know I'm easily discoverable!

My interest in ExPex stems from the practice which the more serious/scholarly singers I know undertake of getting to understand every word of any opera libretto or song text which they may be singing. There are a series of books by Castel for many of the major operas which provide a three-line "gloss" of original language, IPA for sung pronunciation, and English word by word.

Whilst these are useful, many less well-known operas are not available, and at any rate I find it informative to produce my own translations, especially as it's mostly poetry rather than prose.

Because I also normally pencil a word-by-word and the odd phonetic reminder into the score, it's fairly natural for me to use the n-level style, as, with musical dynamics, articulations, etc, I am sort of thinking of "words with bits attached" just like "notes with bits attached".

It also means I can paste a single language libretto into a text editor and use some find/replace magic for little, but constant words like 

Peter Aisher | Tenor
www.peteraisher.com

**Comment by peteraisher** [comment]
Hi John,

Nice to know I'm easily discoverable!

My interest in ExPex stems from the practice which the more serious/scholarly singers I know undertake of getting to understand every word of any opera libretto or song text which they may be singing. There are a series of books by Castel for many of the major operas which provide a three-line "gloss" of original language, IPA for sung pronunciation, and English word by word.

Whilst these are useful, many less well-known operas are not available, and at any rate I find it informative to produce my own translations, especially as it's mostly poetry rather than prose.

Because I also normally pencil a word-by-word and the odd phonetic reminder into the score, it's fairly natural for me to use the n-level style, as, with musical dynamics, articulations, etc, I am sort of thinking of "words with bits attached" just like "notes with bits attached".

It also means I can paste a single language libretto into a text editor and use some find/replace magic for little, but constant words like "the" and "and" etc.

Thanks for looking into it and I'm glad my unusualness has been helpful in spotting a bug!

All best,

Peter

Peter Aisher | Tenor
www.peteraisher.com

**Comment by frampton** [comment]
Subject:   Re: [ExPex] glftpos=right option broken for nlevel gloss (#2)
To:        frampton/ExPex 
<reply@reply.github.com>
Cc:
Bcc:
Reply-To:
-=-=-=-=-=-=-=-=-=# Don't remove this line #=-=-=-=-=-=-=-=-=-
Subject:   Re: [ExPex] glftpos=right option broken for nlevel gloss (#2)
To:        frampton/ExPex 
<reply@reply.github.com>
Cc:
Bcc:
Reply-To:
-=-=-=-=-=-=-=-=-=# Don't remove this line #=-=-=-=-=-=-=-=-=-


I have discovered what the problem is, but have not fixed it yet.  It 
seems that
I added the glftpos options before I added the nlevel style glosses.  So 
setting
glftpos assumes that the gloss is in the older wrap style.

I don't think it will be very hard to fix.  That's next.

After I get it working, perhaps you can send me a sample glossed libretto.

Best,
John

If you want, you can send email directly to: j.frampton@neu.edu

**Comment by frampton** [comment]
Subject:   Re: [ExPex] glftpos=right option broken for nlevel gloss (#2)
To:        frampton/ExPex 
<reply@reply.github.com>
Cc:
Bcc:
Reply-To:
-=-=-=-=-=-=-=-=-=# Don't remove this line #=-=-=-=-=-=-=-=-=-

glftpos=right is now compatible with glstyle=nlevel

The new version is on Github, but I am also attaching the new files.  Of 
course, I am anxiously awaiting reports of new bugs that killing some of 
the old ones uncovers.

Enjoy,
John
\ProvidesPackage{expex}%
  [2015/01/06 v5.0d LaTex wrapper for expex.tex (JF)]
\RequirePackage{xkeyval}
\input expex
\endinput

**Comment by frampton** [comment]
Did you get a chance to look at the ExPex fix?

**Comment by peteraisher** [comment]
Hi John,

I had a play around but there seems to be a par break getting in after the gloss itself when using glftpos=right — but the next paragraph containing the free translation is indented by the amount of sssep if that helps with diagnosis?

In the meantime, I've had success by uncommenting the bit marked experimental in ExPex.tex and enclosing the contents of glft in {}, which works for me with no issues at the moment.

Wasn't sure if it was some other package interfering, and didn't want to bother you until I'd tried a minimal example, which I now have, and the par break remains.

From the code it looks like it's happening when the code for nlevel+right switches over to nlevel+below at the end of the gloss, which makes sense as there's a \par inside the definition of \gl@nlevel@below@end, which is called from inside \gl@nlevel@right@medial — could that be the case?

All best, and thanks again for your help,

Peter



Peter Aisher | Tenor
www.peteraisher.com

**Comment by frampton** [comment]
Hi Peter,

I’m not sure what the problem is.  I’m attaching a demo file that seems to do what is expected.  Perhaps you could run it and tell me if there is a problem for you.  It uses no packages other than expex.  If there is no problem with the demo file, you’ll have to send me a minimal example which shows the problem.  Minimal means you should make it as simple as possible and use no packages other than those that are needed to illustrate the problem.  I am assuming you use Latex, so I sent a Latex file.


-          John

**Comment by peteraisher** [comment]
Sorry, I should have mentioned that I'm using \exdisplay rather than \ex as I don't need/want the numbers and indentation. Your example (and mine if I switch to \ex) works perfectly. I had assumed that the environment was internally the same (i.e. \ex prints an example number and then typesets the remainder exactly as \exdisplay) which is why I didn't mention it.

For a minimal example, simply change yours to \exdisplay.

Sorry if I've led you down a blind alley!

Thanks,

Peter


Peter Aisher | Tenor
www.peteraisher.com

**Comment by frampton** [comment]
A shock!  I certainly see the problem.

I’ll fix it tonight or tomorrow.

- John

**Comment by frampton** [comment]
Hi Peter,

I think the attached will fix the problem.  It hasn’t been pushed to github yet.  The glossing code is beginning to look like spaghetti.  I have to go in and
clean up the code before I push it to github and put it on CTAN.

As usual, I await your entomological comments.

Best,
John

**Comment by frampton** [comment]
Any further comments before I give it my blessings and send it off to CTAN?

**Comment by peteraisher** [comment]
Hi, sorry to take so long to get back to you, I've been rather snowed under. Don't let me hold you back from sending it to CTAN, I'm sure your testing is more thorough than mine!


Peter Aisher | Tenor
www.peteraisher.com

**Comment by frampton** [comment]
OK, thanks.

Maybe sometime you could send me an annotated libretto, it would be a good example to put in a future User’s Guide.  It does not have to be in Tex, I can do that and send it back to you to see if I got it right.
